
name: Timecheck

# Controls when the workflow will run
on:
# Remove following two comments to run this action on daily basis.
#    schedule:
#      - cron: '0 0 * * *'

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    # Using the latest ubuntu for the run
    runs-on: ubuntu-latest
    
    
    steps:
      - uses: actions/checkout@v4
      
      # Capturing the start time
      - name: Capture Start Time
        id: start-time
        run: echo "::set-output name=time::$(date +'%Y-%m-%d-%H-%M-%S')"
