name: Add two numbers

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Add two numbers
        run: |
          num1=10
          num2=20
          sum=$(($num1 + $num2))
          echo "Sum of $num1 and $num2 is $sum" > output.txt
          echo "${{ vars.URL }}"
          

      - name: Upload output.txt
        uses: actions/upload-artifact@v3
        with:
          name: output.txt
          path: ${{ vars.URL }}_yoyo.txt
